# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photos | Andrejs Jaudzems"
subtitle: "A space for my photographs"
author:  "Andrejs Jaudzems"
header:
 title: "Photos"
 subtitle: "A space for my photographs"
footer:
 name: "About"
 bio: "An engineer most of the time, photographer the rest of the time. If you've made it here, you probably know the rest of my story."
social_urls:
  instagram: "https://www.instagram.com/andrejsjaudzems"
