# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photos | Andrejs Jaudzems"
subtitle: "A space for my photographs"
author:  "Andrejs Jaudzems"
header:
 title: "Andrejs Jaudzems"
 subtitle: ""
footer:
 name: "Andrejs Jaudzems"
 bio: "An engineer most of the time, photographer and horse spotter the rest of the time.<br><br>Shot on Canon 5D Mark III + iPhone 13 Pro + Pentax K200D"
social_urls:
  instagram: "https://www.instagram.com/andrejsjaudzems"
  linkedin: "https://www.linkedin.com/in/andrejs-jaudzems"
