# Gallery configs
# Main
gallery_main_image_fulls_loc: "/images/gallery-main/fulls"
gallery_main_image_thumbs_loc: "/images/gallery-main/thumbs"

# Horses
gallery_horses_image_fulls_loc: "/images/gallery-horses/fulls"
gallery_horses_image_thumbs_loc: "/images/gallery-horses/thumbs"

# Nature
gallery_nature_image_fulls_loc: "/images/gallery-nature/fulls"
gallery_nature_image_thumbs_loc: "/images/gallery-nature/thumbs"

# Entertainment
gallery_entertainment_image_fulls_loc: "/images/gallery-entertainment/fulls"
gallery_entertainment_image_thumbs_loc: "/images/gallery-entertainment/thumbs"

# Landscape
gallery_landscape_image_fulls_loc: "/images/gallery-landscape/fulls"
gallery_landscape_image_thumbs_loc: "/images/gallery-landscape/thumbs"

# People-1
gallery_people-1_image_fulls_loc: "/images/gallery-people/people-1/fulls"
gallery_people-1_image_thumbs_loc: "/images/gallery-people/people-1/thumbs"

# People-2
gallery_people-2_image_fulls_loc: "/images/gallery-people/people-2/fulls"
gallery_people-2_image_thumbs_loc: "/images/gallery-people/people-2/thumbs"

# People-3
gallery_people-3_image_fulls_loc: "/images/gallery-people/people-3/fulls"
gallery_people-3_image_thumbs_loc: "/images/gallery-people/people-3/thumbs"

# UI configs
title: "Photos | Andrejs Jaudzems"
subtitle: "A space for my photographs"
author:  "Andrejs Jaudzems"
header:
 title: "Andrejs Jaudzems"
 subtitle: ""
footer:
 name: "Andrejs Jaudzems"
 bio: "An engineer most of the time, photographer and horse spotter the rest of the time.<br><br>Shot on Canon 5D Mark III + iPhone 13 Pro + Pentax K200D"
social_urls:
  instagram: "https://www.instagram.com/andrejsjaudzems"
  linkedin: "https://www.linkedin.com/in/andrejs-jaudzems"
